name: SpamOnleyici
options:
  bundleIdPrefix: com.yourcompany
settings:
  MARKETING_VERSION: "1.0"
  CURRENT_PROJECT_VERSION: "1"
  CODE_SIGN_STYLE: "Manual"
  IPHONEOS_DEPLOYMENT_TARGET: "17.0"
  GENERATE_INFOPLIST_FILE: "YES"

targets:
  SpamOnleyici:
    type: application
    platform: iOS
    sources:
      - path: ios/App
      - path: ios/App/DataManagerWrapper.swift
      - path: ios/Shared
      - path: ml/SpamClassifier.mlmodel
      - path: ml/vocab.json
    entitlements:
      path: ios/App/SpamOnleyici.entitlements
      properties:
        com.apple.security.application-groups: ["group.com.yourcompany.junkman"]
    info:
      path: ios/App/Info.plist
      properties:
        CFBundleDisplayName: "SpamÖnleyici"
        CFBundleShortVersionString: "1.0"
        CFBundleVersion: "1"
        UILaunchScreen: {}
        UISupportedInterfaceOrientations:
          - UIInterfaceOrientationPortrait
        colors: []
        UIDeviceFamily: [1, 2]
        LSRequiresIPhoneOS: true
        UIApplicationSceneManifest:
          UIApplicationSupportsMultipleScenes: false
    dependencies:
      - target: MessageFilterExtension
        embed: true
    settings:
      PRODUCT_BUNDLE_IDENTIFIER: "com.yourcompany.spamonleyici"
      INFOPLIST_KEY_CFBundlePackageType: "APPL"
      
  MessageFilterExtension:
    type: app-extension
    platform: iOS
    sources:
      - path: ios/Extension
      - path: ios/Shared
      - path: ml/SpamClassifier.mlmodel
      - path: ml/vocab.json
    entitlements:
      path: ios/Extension/MessageFilterExtension.entitlements
      properties:
        com.apple.security.application-groups: ["group.com.yourcompany.junkman"]
    dependencies:
      - framework: IdentityLookup.framework
      - framework: CoreML.framework
    settings:
      APPLICATION_EXTENSION_API_ONLY: "YES"
      PRODUCT_BUNDLE_IDENTIFIER: "com.yourcompany.spamonleyici.extension"
      INFOPLIST_KEY_CFBundlePackageType: "XPC!"
    info:
      path: ios/Extension/Info.plist
      properties:
        CFBundleDisplayName: "Message Filter"
        CFBundleShortVersionString: "1.0"
        CFBundleVersion: "1"
        UIDeviceFamily: [1, 2]
        NSExtension:
          NSExtensionPointIdentifier: "com.apple.identitylookup.message-filter"
          NSExtensionPrincipalClass: "MessageFilterExtension"
