name: JunkmanClone
options:
  bundleIdPrefix: com.yourcompany
settings:
  MARKETING_VERSION: 1.0
  CURRENT_PROJECT_VERSION: 1
  DEVELOPMENT_TEAM: "" # Leave empty, will be set by CI or manual signing
  CODE_SIGN_STYLE: Manual # For CI, usually manual or specific ID

targets:
  JunkmanClone:
    type: application
    platform: iOS
    deploymentTarget: "17.0"
    sources:
      - path: ios/App
      - path: ios/Shared
      - path: ml/SpamClassifier.mlmodel
      - path: ml/vocab.json
    entitlements:
      path: ios/App/JunkmanClone.entitlements
    settings:
      INFOPLIST_KEY_UILaunchScreen: {}
      PRODUCT_BUNDLE_IDENTIFIER: com.yourcompany.junkman
      
  MessageFilterExtension:
    type: app-extension
    platform: iOS
    deploymentTarget: "17.0"
    sources:
      - path: ios/Extension
      - path: ios/Shared
      - path: ml/SpamClassifier.mlmodel
      - path: ml/vocab.json
    entitlements:
      path: ios/Extension/MessageFilterExtension.entitlements
    dependencies:
      - target: JunkmanClone 
    settings:
      PRODUCT_BUNDLE_IDENTIFIER: com.yourcompany.junkman.extension
      INFOPLIST_KEY_NSExtension:
        NSExtensionPointIdentifier: "com.apple.identitylookup.message-filter"
        NSExtensionPrincipalClass: "$(PRODUCT_MODULE_NAME).MessageFilterExtension"
