name: SpamOnleyici
options:
  bundleIdPrefix: com.yourcompany
settings:
  MARKETING_VERSION: "1.0"
  CURRENT_PROJECT_VERSION: "1"
  CODE_SIGN_STYLE: "Manual"
  IPHONEOS_DEPLOYMENT_TARGET: "17.0"
  GENERATE_INFOPLIST_FILE: "YES"

targets:
  SpamOnleyici:
    type: application
    platform: iOS
    sources:
      - path: ios/App
      - path: ios/App/DataManagerWrapper.swift
      - path: ios/Shared
      - path: ml/SpamClassifier.mlmodel
      - path: ml/vocab.json
    entitlements:
      path: ios/App/SpamOnleyici.entitlements
    info:
      path: ios/App/Info.plist
    dependencies:
      - target: MessageFilterExtension
        embed: true
    settings:
      PRODUCT_BUNDLE_IDENTIFIER: "com.yourcompany.spamonleyici"
      
  MessageFilterExtension:
    type: app-extension
    platform: iOS
    sources:
      - path: ios/Extension
      - path: ios/Shared
      - path: ml/SpamClassifier.mlmodel
      - path: ml/vocab.json
    entitlements:
      path: ios/Extension/MessageFilterExtension.entitlements
    dependencies:
      - framework: IdentityLookup.framework
      - framework: CoreML.framework
    settings:
      APPLICATION_EXTENSION_API_ONLY: "YES"
      PRODUCT_BUNDLE_IDENTIFIER: "com.yourcompany.spamonleyici.extension"
    info:
      path: ios/Extension/Info.plist
